export const BioRoles = [
    "Audiologist",
    "Certified Athletic Trainer",
    "Certified Nurse Midwife (CNM)",
    "Certified Registered Nurse Anesthetist (CRNA)",
    "Chiropractor",
    "Clinical Nurse Specialist (CNS)",
    "Clinical Research Associate",
    "Clinical Research Coordinator",
    "Community Health Worker",
    "Dental Assistant",
    "Dental Hygienist",
    "Dentist",
    "Epidemiologist",
    "Emergency Medical Technician (EMT)",
    "Genetic Counselor",
    "Health Educator",
    "Health Information Technician",
    "Health Services Manager",
    "Healthcare Consultant",
    "Healthcare Compliance Officer",
    "Licensed Practical Nurse (LPN) / Licensed Vocational Nurse (LVN)",
    "Medical Assistant (MA)",
    "Medical Biller",
    "Medical Coder",
    "Medical Laboratory Technician (MLT)",
    "Medical Office Manager",
    "Medical Records Clerk",
    "Medical Secretary / Administrative Assistant",
    "Medical Technologist (MT)",
    "Nurse Educator",
    "Nurse Manager",
    "Nurse Practitioner (NP)",
    "Occupational Therapist (OT)",
    "Optometrist",
    "Orthotist / Prosthetist",
    "Paramedic",
    "Pathologist",
    "Patient Services Representative",
    "Perfusionist",
    "Physical Therapist (PT)",
    "Physician (e.g., Cardiologist, Dermatologist, Oncologist)",
    "Physician Assistant (PA)",
    "Public Health Nurse",
    "Radiologic Technologist",
    "Registered Nurse (RN)",
    "Rehabilitation Counselor",
    "Respiratory Therapist",
    "Speech-Language Pathologist (SLP)",
    "Surgeon (e.g., Orthopedic Surgeon, Neurosurgeon)",
    "Ultrasound Technician / Diagnostic Medical Sonographer"
  ];